Models/ErrorViewModel.cs
namespace DotnetMvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ListModel.cs
using System.ComponentModel.DataAnnotations;

namespace DotnetMvc.Models;

public class ListModel
{
    public int Id { get; set; }
    public string? Title { get; set; }
    public string? Text { get; set; }
    [DataType(DataType.Date)]
    public DateTime ReleaseDate { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DotnetMvc.Models;

namespace DotnetMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotnetMvc.Data;
using DotnetMvc.Models;

namespace DotnetMvc.Controllers
{
    public class ListController : Controller
    {
        private readonly DotnetMvcContext _context;

        public ListController(DotnetMvcContext context)
        {
            _context = context;
        }

        // GET: List
        public async Task<IActionResult> Index()
        {
              return _context.ListModel != null ? 
                          View(await _context.ListModel.ToListAsync()) :
                          Problem("Entity set 'DotnetMvcContext.ListModel'  is null.");
        }

        // GET: List/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ListModel == null)
            {
                return NotFound();
            }

            var listModel = await _context.ListModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (listModel == null)
            {
                return NotFound();
            }

            return View(listModel);
        }

        // GET: List/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: List/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Text,ReleaseDate")] ListModel listModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(listModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(listModel);
        }

        // GET: List/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ListModel == null)
            {
                return NotFound();
            }

            var listModel = await _context.ListModel.FindAsync(id);
            if (listModel == null)
            {
                return NotFound();
            }
            return View(listModel);
        }

        // POST: List/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Text,ReleaseDate")] ListModel listModel)
        {
            if (id != listModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(listModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ListModelExists(listModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(listModel);
        }

        // GET: List/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ListModel == null)
            {
                return NotFound();
            }

            var listModel = await _context.ListModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (listModel == null)
            {
                return NotFound();
            }

            return View(listModel);
        }

        // POST: List/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ListModel == null)
            {
                return Problem("Entity set 'DotnetMvcContext.ListModel'  is null.");
            }
            var listModel = await _context.ListModel.FindAsync(id);
            if (listModel != null)
            {
                _context.ListModel.Remove(listModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ListModelExists(int id)
        {
          return (_context.ListModel?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-start my-5 mx-2">
    <h1 class="display-4">Bem vindo!</h1>
    <p>
        Essa é minha primeira aplicação com .net e c#
        </br>
        Crie, liste, edite e exclua anotações.
       
        Acesse "Lista" para verificar as opções.

    </p>
    
</div>

Views/List/Create.cshtml
@model DotnetMvc.Models.ListModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>ListModel</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="p-2 form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="bg-dark bg-opacity-50 text-white form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="bg-dark bg-opacity-50 text-white  form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="bg-dark bg-opacity-50 text-white form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="p-2 text-white" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/List/Delete.cshtml
@model DotnetMvc.Models.ListModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>
Tem certeza de que deseja excluir isso?
</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10 text-break">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10 text-break">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="text-white" asp-action="Index">Back to List</a>
    </form>
</div>

Views/List/Details.cshtml
@model DotnetMvc.Models.ListModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ListModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10 text-break">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10 text-break">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
    </dl>
</div>
<div>
    <a class="text-white"  asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a class="text-white"  asp-action="Index">Back to List</a>
</div>

Views/List/Edit.cshtml
@model DotnetMvc.Models.ListModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ListModel</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="p-2 form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="bg-dark bg-opacity-50 text-white form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="bg-dark bg-opacity-50 text-white form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="bg-dark bg-opacity-50 text-white form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            <div class="p-2 form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="p-2 text-white" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/List/Index.cshtml
@model IEnumerable<DotnetMvc.Models.ListModel>

@{
    ViewData["Title"] = "Lista";
}

<h1>Anotações</h1>

<p>
    <a class="text-white" asp-action="Create">Create New</a>
</p>
<table class="table text-white">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="text-truncate" style="max-width: 8rem;">
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td class="text-truncate" style="max-width: 14rem;">
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                <a class="text-white" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="text-success" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="text-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dotnet Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DotnetMvc.styles.css" asp-append-version="true" />
</head>
<body class="bg-black text-white">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dotnet Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Pagina Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="List" asp-action="Index">Lista</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted ">
        <div class="container text-white">
            &copy; 2023 - Dotnet Mvc - <a target="_blank" href="https://github.com/GislaineFrandalozo">Gislaine Frandalozo</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>